/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropiedadesRouteImport } from './routes/propiedades'
import { Route as PrestamosRouteImport } from './routes/prestamos'
import { Route as LocalesRouteImport } from './routes/locales'
import { Route as CalcularCreditoRouteImport } from './routes/calcular-credito'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadesIndexRouteImport } from './routes/propiedades.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PropiedadesPropertyIdRouteImport } from './routes/propiedades.$propertyId'
import { Route as PrestamosRemodelacionDeInmuebleRouteImport } from './routes/prestamos.remodelacion-de-inmueble'
import { Route as PrestamosPrestamoPersonalRouteImport } from './routes/prestamos.prestamo-personal'
import { Route as PrestamosConsolidacionDeDeudasRouteImport } from './routes/prestamos.consolidacion-de-deudas'
import { Route as PrestamosCapitalDeInversionRouteImport } from './routes/prestamos.capital-de-inversion'
import { Route as LocalesSlugRouteImport } from './routes/locales.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PrestamosRemodelacionDeInmuebleIndexRouteImport } from './routes/prestamos.remodelacion-de-inmueble.index'
import { Route as PrestamosPrestamoPersonalIndexRouteImport } from './routes/prestamos.prestamo-personal.index'
import { Route as PrestamosConsolidacionDeDeudasIndexRouteImport } from './routes/prestamos.consolidacion-de-deudas.index'
import { Route as PrestamosCapitalDeInversionIndexRouteImport } from './routes/prestamos.capital-de-inversion.index'
import { Route as PrestamosRemodelacionDeInmuebleLocationRouteImport } from './routes/prestamos.remodelacion-de-inmueble.$location'
import { Route as PrestamosPrestamoPersonalLocationRouteImport } from './routes/prestamos.prestamo-personal.$location'
import { Route as PrestamosConsolidacionDeDeudasLocationRouteImport } from './routes/prestamos.consolidacion-de-deudas.$location'
import { Route as PrestamosCapitalDeInversionLocationRouteImport } from './routes/prestamos.capital-de-inversion.$location'

const PropiedadesRoute = PropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestamosRoute = PrestamosRouteImport.update({
  id: '/prestamos',
  path: '/prestamos',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalesRoute = LocalesRouteImport.update({
  id: '/locales',
  path: '/locales',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcularCreditoRoute = CalcularCreditoRouteImport.update({
  id: '/calcular-credito',
  path: '/calcular-credito',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIndexRoute = PropiedadesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropiedadesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const PropiedadesPropertyIdRoute = PropiedadesPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => PropiedadesRoute,
} as any)
const PrestamosRemodelacionDeInmuebleRoute =
  PrestamosRemodelacionDeInmuebleRouteImport.update({
    id: '/remodelacion-de-inmueble',
    path: '/remodelacion-de-inmueble',
    getParentRoute: () => PrestamosRoute,
  } as any)
const PrestamosPrestamoPersonalRoute =
  PrestamosPrestamoPersonalRouteImport.update({
    id: '/prestamo-personal',
    path: '/prestamo-personal',
    getParentRoute: () => PrestamosRoute,
  } as any)
const PrestamosConsolidacionDeDeudasRoute =
  PrestamosConsolidacionDeDeudasRouteImport.update({
    id: '/consolidacion-de-deudas',
    path: '/consolidacion-de-deudas',
    getParentRoute: () => PrestamosRoute,
  } as any)
const PrestamosCapitalDeInversionRoute =
  PrestamosCapitalDeInversionRouteImport.update({
    id: '/capital-de-inversion',
    path: '/capital-de-inversion',
    getParentRoute: () => PrestamosRoute,
  } as any)
const LocalesSlugRoute = LocalesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocalesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const PrestamosRemodelacionDeInmuebleIndexRoute =
  PrestamosRemodelacionDeInmuebleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrestamosRemodelacionDeInmuebleRoute,
  } as any)
const PrestamosPrestamoPersonalIndexRoute =
  PrestamosPrestamoPersonalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrestamosPrestamoPersonalRoute,
  } as any)
const PrestamosConsolidacionDeDeudasIndexRoute =
  PrestamosConsolidacionDeDeudasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrestamosConsolidacionDeDeudasRoute,
  } as any)
const PrestamosCapitalDeInversionIndexRoute =
  PrestamosCapitalDeInversionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrestamosCapitalDeInversionRoute,
  } as any)
const PrestamosRemodelacionDeInmuebleLocationRoute =
  PrestamosRemodelacionDeInmuebleLocationRouteImport.update({
    id: '/$location',
    path: '/$location',
    getParentRoute: () => PrestamosRemodelacionDeInmuebleRoute,
  } as any)
const PrestamosPrestamoPersonalLocationRoute =
  PrestamosPrestamoPersonalLocationRouteImport.update({
    id: '/$location',
    path: '/$location',
    getParentRoute: () => PrestamosPrestamoPersonalRoute,
  } as any)
const PrestamosConsolidacionDeDeudasLocationRoute =
  PrestamosConsolidacionDeDeudasLocationRouteImport.update({
    id: '/$location',
    path: '/$location',
    getParentRoute: () => PrestamosConsolidacionDeDeudasRoute,
  } as any)
const PrestamosCapitalDeInversionLocationRoute =
  PrestamosCapitalDeInversionLocationRouteImport.update({
    id: '/$location',
    path: '/$location',
    getParentRoute: () => PrestamosCapitalDeInversionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/calcular-credito': typeof CalcularCreditoRoute
  '/locales': typeof LocalesRouteWithChildren
  '/prestamos': typeof PrestamosRouteWithChildren
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/locales/$slug': typeof LocalesSlugRoute
  '/prestamos/capital-de-inversion': typeof PrestamosCapitalDeInversionRouteWithChildren
  '/prestamos/consolidacion-de-deudas': typeof PrestamosConsolidacionDeDeudasRouteWithChildren
  '/prestamos/prestamo-personal': typeof PrestamosPrestamoPersonalRouteWithChildren
  '/prestamos/remodelacion-de-inmueble': typeof PrestamosRemodelacionDeInmuebleRouteWithChildren
  '/propiedades/$propertyId': typeof PropiedadesPropertyIdRoute
  '/blog/': typeof BlogIndexRoute
  '/propiedades/': typeof PropiedadesIndexRoute
  '/prestamos/capital-de-inversion/$location': typeof PrestamosCapitalDeInversionLocationRoute
  '/prestamos/consolidacion-de-deudas/$location': typeof PrestamosConsolidacionDeDeudasLocationRoute
  '/prestamos/prestamo-personal/$location': typeof PrestamosPrestamoPersonalLocationRoute
  '/prestamos/remodelacion-de-inmueble/$location': typeof PrestamosRemodelacionDeInmuebleLocationRoute
  '/prestamos/capital-de-inversion/': typeof PrestamosCapitalDeInversionIndexRoute
  '/prestamos/consolidacion-de-deudas/': typeof PrestamosConsolidacionDeDeudasIndexRoute
  '/prestamos/prestamo-personal/': typeof PrestamosPrestamoPersonalIndexRoute
  '/prestamos/remodelacion-de-inmueble/': typeof PrestamosRemodelacionDeInmuebleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calcular-credito': typeof CalcularCreditoRoute
  '/locales': typeof LocalesRouteWithChildren
  '/prestamos': typeof PrestamosRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/locales/$slug': typeof LocalesSlugRoute
  '/propiedades/$propertyId': typeof PropiedadesPropertyIdRoute
  '/blog': typeof BlogIndexRoute
  '/propiedades': typeof PropiedadesIndexRoute
  '/prestamos/capital-de-inversion/$location': typeof PrestamosCapitalDeInversionLocationRoute
  '/prestamos/consolidacion-de-deudas/$location': typeof PrestamosConsolidacionDeDeudasLocationRoute
  '/prestamos/prestamo-personal/$location': typeof PrestamosPrestamoPersonalLocationRoute
  '/prestamos/remodelacion-de-inmueble/$location': typeof PrestamosRemodelacionDeInmuebleLocationRoute
  '/prestamos/capital-de-inversion': typeof PrestamosCapitalDeInversionIndexRoute
  '/prestamos/consolidacion-de-deudas': typeof PrestamosConsolidacionDeDeudasIndexRoute
  '/prestamos/prestamo-personal': typeof PrestamosPrestamoPersonalIndexRoute
  '/prestamos/remodelacion-de-inmueble': typeof PrestamosRemodelacionDeInmuebleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/calcular-credito': typeof CalcularCreditoRoute
  '/locales': typeof LocalesRouteWithChildren
  '/prestamos': typeof PrestamosRouteWithChildren
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/locales/$slug': typeof LocalesSlugRoute
  '/prestamos/capital-de-inversion': typeof PrestamosCapitalDeInversionRouteWithChildren
  '/prestamos/consolidacion-de-deudas': typeof PrestamosConsolidacionDeDeudasRouteWithChildren
  '/prestamos/prestamo-personal': typeof PrestamosPrestamoPersonalRouteWithChildren
  '/prestamos/remodelacion-de-inmueble': typeof PrestamosRemodelacionDeInmuebleRouteWithChildren
  '/propiedades/$propertyId': typeof PropiedadesPropertyIdRoute
  '/blog/': typeof BlogIndexRoute
  '/propiedades/': typeof PropiedadesIndexRoute
  '/prestamos/capital-de-inversion/$location': typeof PrestamosCapitalDeInversionLocationRoute
  '/prestamos/consolidacion-de-deudas/$location': typeof PrestamosConsolidacionDeDeudasLocationRoute
  '/prestamos/prestamo-personal/$location': typeof PrestamosPrestamoPersonalLocationRoute
  '/prestamos/remodelacion-de-inmueble/$location': typeof PrestamosRemodelacionDeInmuebleLocationRoute
  '/prestamos/capital-de-inversion/': typeof PrestamosCapitalDeInversionIndexRoute
  '/prestamos/consolidacion-de-deudas/': typeof PrestamosConsolidacionDeDeudasIndexRoute
  '/prestamos/prestamo-personal/': typeof PrestamosPrestamoPersonalIndexRoute
  '/prestamos/remodelacion-de-inmueble/': typeof PrestamosRemodelacionDeInmuebleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/calcular-credito'
    | '/locales'
    | '/prestamos'
    | '/propiedades'
    | '/blog/$slug'
    | '/locales/$slug'
    | '/prestamos/capital-de-inversion'
    | '/prestamos/consolidacion-de-deudas'
    | '/prestamos/prestamo-personal'
    | '/prestamos/remodelacion-de-inmueble'
    | '/propiedades/$propertyId'
    | '/blog/'
    | '/propiedades/'
    | '/prestamos/capital-de-inversion/$location'
    | '/prestamos/consolidacion-de-deudas/$location'
    | '/prestamos/prestamo-personal/$location'
    | '/prestamos/remodelacion-de-inmueble/$location'
    | '/prestamos/capital-de-inversion/'
    | '/prestamos/consolidacion-de-deudas/'
    | '/prestamos/prestamo-personal/'
    | '/prestamos/remodelacion-de-inmueble/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calcular-credito'
    | '/locales'
    | '/prestamos'
    | '/blog/$slug'
    | '/locales/$slug'
    | '/propiedades/$propertyId'
    | '/blog'
    | '/propiedades'
    | '/prestamos/capital-de-inversion/$location'
    | '/prestamos/consolidacion-de-deudas/$location'
    | '/prestamos/prestamo-personal/$location'
    | '/prestamos/remodelacion-de-inmueble/$location'
    | '/prestamos/capital-de-inversion'
    | '/prestamos/consolidacion-de-deudas'
    | '/prestamos/prestamo-personal'
    | '/prestamos/remodelacion-de-inmueble'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/calcular-credito'
    | '/locales'
    | '/prestamos'
    | '/propiedades'
    | '/blog/$slug'
    | '/locales/$slug'
    | '/prestamos/capital-de-inversion'
    | '/prestamos/consolidacion-de-deudas'
    | '/prestamos/prestamo-personal'
    | '/prestamos/remodelacion-de-inmueble'
    | '/propiedades/$propertyId'
    | '/blog/'
    | '/propiedades/'
    | '/prestamos/capital-de-inversion/$location'
    | '/prestamos/consolidacion-de-deudas/$location'
    | '/prestamos/prestamo-personal/$location'
    | '/prestamos/remodelacion-de-inmueble/$location'
    | '/prestamos/capital-de-inversion/'
    | '/prestamos/consolidacion-de-deudas/'
    | '/prestamos/prestamo-personal/'
    | '/prestamos/remodelacion-de-inmueble/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalcularCreditoRoute: typeof CalcularCreditoRoute
  LocalesRoute: typeof LocalesRouteWithChildren
  PrestamosRoute: typeof PrestamosRouteWithChildren
  PropiedadesRoute: typeof PropiedadesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propiedades': {
      id: '/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestamos': {
      id: '/prestamos'
      path: '/prestamos'
      fullPath: '/prestamos'
      preLoaderRoute: typeof PrestamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locales': {
      id: '/locales'
      path: '/locales'
      fullPath: '/locales'
      preLoaderRoute: typeof LocalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcular-credito': {
      id: '/calcular-credito'
      path: '/calcular-credito'
      fullPath: '/calcular-credito'
      preLoaderRoute: typeof CalcularCreditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/': {
      id: '/propiedades/'
      path: '/'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PropiedadesIndexRouteImport
      parentRoute: typeof PropiedadesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/propiedades/$propertyId': {
      id: '/propiedades/$propertyId'
      path: '/$propertyId'
      fullPath: '/propiedades/$propertyId'
      preLoaderRoute: typeof PropiedadesPropertyIdRouteImport
      parentRoute: typeof PropiedadesRoute
    }
    '/prestamos/remodelacion-de-inmueble': {
      id: '/prestamos/remodelacion-de-inmueble'
      path: '/remodelacion-de-inmueble'
      fullPath: '/prestamos/remodelacion-de-inmueble'
      preLoaderRoute: typeof PrestamosRemodelacionDeInmuebleRouteImport
      parentRoute: typeof PrestamosRoute
    }
    '/prestamos/prestamo-personal': {
      id: '/prestamos/prestamo-personal'
      path: '/prestamo-personal'
      fullPath: '/prestamos/prestamo-personal'
      preLoaderRoute: typeof PrestamosPrestamoPersonalRouteImport
      parentRoute: typeof PrestamosRoute
    }
    '/prestamos/consolidacion-de-deudas': {
      id: '/prestamos/consolidacion-de-deudas'
      path: '/consolidacion-de-deudas'
      fullPath: '/prestamos/consolidacion-de-deudas'
      preLoaderRoute: typeof PrestamosConsolidacionDeDeudasRouteImport
      parentRoute: typeof PrestamosRoute
    }
    '/prestamos/capital-de-inversion': {
      id: '/prestamos/capital-de-inversion'
      path: '/capital-de-inversion'
      fullPath: '/prestamos/capital-de-inversion'
      preLoaderRoute: typeof PrestamosCapitalDeInversionRouteImport
      parentRoute: typeof PrestamosRoute
    }
    '/locales/$slug': {
      id: '/locales/$slug'
      path: '/$slug'
      fullPath: '/locales/$slug'
      preLoaderRoute: typeof LocalesSlugRouteImport
      parentRoute: typeof LocalesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/prestamos/remodelacion-de-inmueble/': {
      id: '/prestamos/remodelacion-de-inmueble/'
      path: '/'
      fullPath: '/prestamos/remodelacion-de-inmueble/'
      preLoaderRoute: typeof PrestamosRemodelacionDeInmuebleIndexRouteImport
      parentRoute: typeof PrestamosRemodelacionDeInmuebleRoute
    }
    '/prestamos/prestamo-personal/': {
      id: '/prestamos/prestamo-personal/'
      path: '/'
      fullPath: '/prestamos/prestamo-personal/'
      preLoaderRoute: typeof PrestamosPrestamoPersonalIndexRouteImport
      parentRoute: typeof PrestamosPrestamoPersonalRoute
    }
    '/prestamos/consolidacion-de-deudas/': {
      id: '/prestamos/consolidacion-de-deudas/'
      path: '/'
      fullPath: '/prestamos/consolidacion-de-deudas/'
      preLoaderRoute: typeof PrestamosConsolidacionDeDeudasIndexRouteImport
      parentRoute: typeof PrestamosConsolidacionDeDeudasRoute
    }
    '/prestamos/capital-de-inversion/': {
      id: '/prestamos/capital-de-inversion/'
      path: '/'
      fullPath: '/prestamos/capital-de-inversion/'
      preLoaderRoute: typeof PrestamosCapitalDeInversionIndexRouteImport
      parentRoute: typeof PrestamosCapitalDeInversionRoute
    }
    '/prestamos/remodelacion-de-inmueble/$location': {
      id: '/prestamos/remodelacion-de-inmueble/$location'
      path: '/$location'
      fullPath: '/prestamos/remodelacion-de-inmueble/$location'
      preLoaderRoute: typeof PrestamosRemodelacionDeInmuebleLocationRouteImport
      parentRoute: typeof PrestamosRemodelacionDeInmuebleRoute
    }
    '/prestamos/prestamo-personal/$location': {
      id: '/prestamos/prestamo-personal/$location'
      path: '/$location'
      fullPath: '/prestamos/prestamo-personal/$location'
      preLoaderRoute: typeof PrestamosPrestamoPersonalLocationRouteImport
      parentRoute: typeof PrestamosPrestamoPersonalRoute
    }
    '/prestamos/consolidacion-de-deudas/$location': {
      id: '/prestamos/consolidacion-de-deudas/$location'
      path: '/$location'
      fullPath: '/prestamos/consolidacion-de-deudas/$location'
      preLoaderRoute: typeof PrestamosConsolidacionDeDeudasLocationRouteImport
      parentRoute: typeof PrestamosConsolidacionDeDeudasRoute
    }
    '/prestamos/capital-de-inversion/$location': {
      id: '/prestamos/capital-de-inversion/$location'
      path: '/$location'
      fullPath: '/prestamos/capital-de-inversion/$location'
      preLoaderRoute: typeof PrestamosCapitalDeInversionLocationRouteImport
      parentRoute: typeof PrestamosCapitalDeInversionRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface LocalesRouteChildren {
  LocalesSlugRoute: typeof LocalesSlugRoute
}

const LocalesRouteChildren: LocalesRouteChildren = {
  LocalesSlugRoute: LocalesSlugRoute,
}

const LocalesRouteWithChildren =
  LocalesRoute._addFileChildren(LocalesRouteChildren)

interface PrestamosCapitalDeInversionRouteChildren {
  PrestamosCapitalDeInversionLocationRoute: typeof PrestamosCapitalDeInversionLocationRoute
  PrestamosCapitalDeInversionIndexRoute: typeof PrestamosCapitalDeInversionIndexRoute
}

const PrestamosCapitalDeInversionRouteChildren: PrestamosCapitalDeInversionRouteChildren =
  {
    PrestamosCapitalDeInversionLocationRoute:
      PrestamosCapitalDeInversionLocationRoute,
    PrestamosCapitalDeInversionIndexRoute:
      PrestamosCapitalDeInversionIndexRoute,
  }

const PrestamosCapitalDeInversionRouteWithChildren =
  PrestamosCapitalDeInversionRoute._addFileChildren(
    PrestamosCapitalDeInversionRouteChildren,
  )

interface PrestamosConsolidacionDeDeudasRouteChildren {
  PrestamosConsolidacionDeDeudasLocationRoute: typeof PrestamosConsolidacionDeDeudasLocationRoute
  PrestamosConsolidacionDeDeudasIndexRoute: typeof PrestamosConsolidacionDeDeudasIndexRoute
}

const PrestamosConsolidacionDeDeudasRouteChildren: PrestamosConsolidacionDeDeudasRouteChildren =
  {
    PrestamosConsolidacionDeDeudasLocationRoute:
      PrestamosConsolidacionDeDeudasLocationRoute,
    PrestamosConsolidacionDeDeudasIndexRoute:
      PrestamosConsolidacionDeDeudasIndexRoute,
  }

const PrestamosConsolidacionDeDeudasRouteWithChildren =
  PrestamosConsolidacionDeDeudasRoute._addFileChildren(
    PrestamosConsolidacionDeDeudasRouteChildren,
  )

interface PrestamosPrestamoPersonalRouteChildren {
  PrestamosPrestamoPersonalLocationRoute: typeof PrestamosPrestamoPersonalLocationRoute
  PrestamosPrestamoPersonalIndexRoute: typeof PrestamosPrestamoPersonalIndexRoute
}

const PrestamosPrestamoPersonalRouteChildren: PrestamosPrestamoPersonalRouteChildren =
  {
    PrestamosPrestamoPersonalLocationRoute:
      PrestamosPrestamoPersonalLocationRoute,
    PrestamosPrestamoPersonalIndexRoute: PrestamosPrestamoPersonalIndexRoute,
  }

const PrestamosPrestamoPersonalRouteWithChildren =
  PrestamosPrestamoPersonalRoute._addFileChildren(
    PrestamosPrestamoPersonalRouteChildren,
  )

interface PrestamosRemodelacionDeInmuebleRouteChildren {
  PrestamosRemodelacionDeInmuebleLocationRoute: typeof PrestamosRemodelacionDeInmuebleLocationRoute
  PrestamosRemodelacionDeInmuebleIndexRoute: typeof PrestamosRemodelacionDeInmuebleIndexRoute
}

const PrestamosRemodelacionDeInmuebleRouteChildren: PrestamosRemodelacionDeInmuebleRouteChildren =
  {
    PrestamosRemodelacionDeInmuebleLocationRoute:
      PrestamosRemodelacionDeInmuebleLocationRoute,
    PrestamosRemodelacionDeInmuebleIndexRoute:
      PrestamosRemodelacionDeInmuebleIndexRoute,
  }

const PrestamosRemodelacionDeInmuebleRouteWithChildren =
  PrestamosRemodelacionDeInmuebleRoute._addFileChildren(
    PrestamosRemodelacionDeInmuebleRouteChildren,
  )

interface PrestamosRouteChildren {
  PrestamosCapitalDeInversionRoute: typeof PrestamosCapitalDeInversionRouteWithChildren
  PrestamosConsolidacionDeDeudasRoute: typeof PrestamosConsolidacionDeDeudasRouteWithChildren
  PrestamosPrestamoPersonalRoute: typeof PrestamosPrestamoPersonalRouteWithChildren
  PrestamosRemodelacionDeInmuebleRoute: typeof PrestamosRemodelacionDeInmuebleRouteWithChildren
}

const PrestamosRouteChildren: PrestamosRouteChildren = {
  PrestamosCapitalDeInversionRoute:
    PrestamosCapitalDeInversionRouteWithChildren,
  PrestamosConsolidacionDeDeudasRoute:
    PrestamosConsolidacionDeDeudasRouteWithChildren,
  PrestamosPrestamoPersonalRoute: PrestamosPrestamoPersonalRouteWithChildren,
  PrestamosRemodelacionDeInmuebleRoute:
    PrestamosRemodelacionDeInmuebleRouteWithChildren,
}

const PrestamosRouteWithChildren = PrestamosRoute._addFileChildren(
  PrestamosRouteChildren,
)

interface PropiedadesRouteChildren {
  PropiedadesPropertyIdRoute: typeof PropiedadesPropertyIdRoute
  PropiedadesIndexRoute: typeof PropiedadesIndexRoute
}

const PropiedadesRouteChildren: PropiedadesRouteChildren = {
  PropiedadesPropertyIdRoute: PropiedadesPropertyIdRoute,
  PropiedadesIndexRoute: PropiedadesIndexRoute,
}

const PropiedadesRouteWithChildren = PropiedadesRoute._addFileChildren(
  PropiedadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CalcularCreditoRoute: CalcularCreditoRoute,
  LocalesRoute: LocalesRouteWithChildren,
  PrestamosRoute: PrestamosRouteWithChildren,
  PropiedadesRoute: PropiedadesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
