/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropiedadesRouteImport } from './routes/propiedades'
import { Route as PrestamosRouteImport } from './routes/prestamos'
import { Route as CalcularCreditoRouteImport } from './routes/calcular-credito'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadesIndexRouteImport } from './routes/propiedades.index'
import { Route as PropiedadesPropertyIdRouteImport } from './routes/propiedades.$propertyId'
import { Route as PrestamosRemodelacionDeInmuebleRouteImport } from './routes/prestamos.remodelacion-de-inmueble'
import { Route as PrestamosPrestamoPersonalRouteImport } from './routes/prestamos.prestamo-personal'
import { Route as PrestamosConsolidacionDeDeudasRouteImport } from './routes/prestamos.consolidacion-de-deudas'
import { Route as PrestamosCapitalDeInversionRouteImport } from './routes/prestamos.capital-de-inversion'

const PropiedadesRoute = PropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestamosRoute = PrestamosRouteImport.update({
  id: '/prestamos',
  path: '/prestamos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcularCreditoRoute = CalcularCreditoRouteImport.update({
  id: '/calcular-credito',
  path: '/calcular-credito',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIndexRoute = PropiedadesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropiedadesRoute,
} as any)
const PropiedadesPropertyIdRoute = PropiedadesPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => PropiedadesRoute,
} as any)
const PrestamosRemodelacionDeInmuebleRoute =
  PrestamosRemodelacionDeInmuebleRouteImport.update({
    id: '/remodelacion-de-inmueble',
    path: '/remodelacion-de-inmueble',
    getParentRoute: () => PrestamosRoute,
  } as any)
const PrestamosPrestamoPersonalRoute =
  PrestamosPrestamoPersonalRouteImport.update({
    id: '/prestamo-personal',
    path: '/prestamo-personal',
    getParentRoute: () => PrestamosRoute,
  } as any)
const PrestamosConsolidacionDeDeudasRoute =
  PrestamosConsolidacionDeDeudasRouteImport.update({
    id: '/consolidacion-de-deudas',
    path: '/consolidacion-de-deudas',
    getParentRoute: () => PrestamosRoute,
  } as any)
const PrestamosCapitalDeInversionRoute =
  PrestamosCapitalDeInversionRouteImport.update({
    id: '/capital-de-inversion',
    path: '/capital-de-inversion',
    getParentRoute: () => PrestamosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calcular-credito': typeof CalcularCreditoRoute
  '/prestamos': typeof PrestamosRouteWithChildren
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/prestamos/capital-de-inversion': typeof PrestamosCapitalDeInversionRoute
  '/prestamos/consolidacion-de-deudas': typeof PrestamosConsolidacionDeDeudasRoute
  '/prestamos/prestamo-personal': typeof PrestamosPrestamoPersonalRoute
  '/prestamos/remodelacion-de-inmueble': typeof PrestamosRemodelacionDeInmuebleRoute
  '/propiedades/$propertyId': typeof PropiedadesPropertyIdRoute
  '/propiedades/': typeof PropiedadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calcular-credito': typeof CalcularCreditoRoute
  '/prestamos': typeof PrestamosRouteWithChildren
  '/prestamos/capital-de-inversion': typeof PrestamosCapitalDeInversionRoute
  '/prestamos/consolidacion-de-deudas': typeof PrestamosConsolidacionDeDeudasRoute
  '/prestamos/prestamo-personal': typeof PrestamosPrestamoPersonalRoute
  '/prestamos/remodelacion-de-inmueble': typeof PrestamosRemodelacionDeInmuebleRoute
  '/propiedades/$propertyId': typeof PropiedadesPropertyIdRoute
  '/propiedades': typeof PropiedadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calcular-credito': typeof CalcularCreditoRoute
  '/prestamos': typeof PrestamosRouteWithChildren
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/prestamos/capital-de-inversion': typeof PrestamosCapitalDeInversionRoute
  '/prestamos/consolidacion-de-deudas': typeof PrestamosConsolidacionDeDeudasRoute
  '/prestamos/prestamo-personal': typeof PrestamosPrestamoPersonalRoute
  '/prestamos/remodelacion-de-inmueble': typeof PrestamosRemodelacionDeInmuebleRoute
  '/propiedades/$propertyId': typeof PropiedadesPropertyIdRoute
  '/propiedades/': typeof PropiedadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calcular-credito'
    | '/prestamos'
    | '/propiedades'
    | '/prestamos/capital-de-inversion'
    | '/prestamos/consolidacion-de-deudas'
    | '/prestamos/prestamo-personal'
    | '/prestamos/remodelacion-de-inmueble'
    | '/propiedades/$propertyId'
    | '/propiedades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calcular-credito'
    | '/prestamos'
    | '/prestamos/capital-de-inversion'
    | '/prestamos/consolidacion-de-deudas'
    | '/prestamos/prestamo-personal'
    | '/prestamos/remodelacion-de-inmueble'
    | '/propiedades/$propertyId'
    | '/propiedades'
  id:
    | '__root__'
    | '/'
    | '/calcular-credito'
    | '/prestamos'
    | '/propiedades'
    | '/prestamos/capital-de-inversion'
    | '/prestamos/consolidacion-de-deudas'
    | '/prestamos/prestamo-personal'
    | '/prestamos/remodelacion-de-inmueble'
    | '/propiedades/$propertyId'
    | '/propiedades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalcularCreditoRoute: typeof CalcularCreditoRoute
  PrestamosRoute: typeof PrestamosRouteWithChildren
  PropiedadesRoute: typeof PropiedadesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propiedades': {
      id: '/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestamos': {
      id: '/prestamos'
      path: '/prestamos'
      fullPath: '/prestamos'
      preLoaderRoute: typeof PrestamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcular-credito': {
      id: '/calcular-credito'
      path: '/calcular-credito'
      fullPath: '/calcular-credito'
      preLoaderRoute: typeof CalcularCreditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/': {
      id: '/propiedades/'
      path: '/'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PropiedadesIndexRouteImport
      parentRoute: typeof PropiedadesRoute
    }
    '/propiedades/$propertyId': {
      id: '/propiedades/$propertyId'
      path: '/$propertyId'
      fullPath: '/propiedades/$propertyId'
      preLoaderRoute: typeof PropiedadesPropertyIdRouteImport
      parentRoute: typeof PropiedadesRoute
    }
    '/prestamos/remodelacion-de-inmueble': {
      id: '/prestamos/remodelacion-de-inmueble'
      path: '/remodelacion-de-inmueble'
      fullPath: '/prestamos/remodelacion-de-inmueble'
      preLoaderRoute: typeof PrestamosRemodelacionDeInmuebleRouteImport
      parentRoute: typeof PrestamosRoute
    }
    '/prestamos/prestamo-personal': {
      id: '/prestamos/prestamo-personal'
      path: '/prestamo-personal'
      fullPath: '/prestamos/prestamo-personal'
      preLoaderRoute: typeof PrestamosPrestamoPersonalRouteImport
      parentRoute: typeof PrestamosRoute
    }
    '/prestamos/consolidacion-de-deudas': {
      id: '/prestamos/consolidacion-de-deudas'
      path: '/consolidacion-de-deudas'
      fullPath: '/prestamos/consolidacion-de-deudas'
      preLoaderRoute: typeof PrestamosConsolidacionDeDeudasRouteImport
      parentRoute: typeof PrestamosRoute
    }
    '/prestamos/capital-de-inversion': {
      id: '/prestamos/capital-de-inversion'
      path: '/capital-de-inversion'
      fullPath: '/prestamos/capital-de-inversion'
      preLoaderRoute: typeof PrestamosCapitalDeInversionRouteImport
      parentRoute: typeof PrestamosRoute
    }
  }
}

interface PrestamosRouteChildren {
  PrestamosCapitalDeInversionRoute: typeof PrestamosCapitalDeInversionRoute
  PrestamosConsolidacionDeDeudasRoute: typeof PrestamosConsolidacionDeDeudasRoute
  PrestamosPrestamoPersonalRoute: typeof PrestamosPrestamoPersonalRoute
  PrestamosRemodelacionDeInmuebleRoute: typeof PrestamosRemodelacionDeInmuebleRoute
}

const PrestamosRouteChildren: PrestamosRouteChildren = {
  PrestamosCapitalDeInversionRoute: PrestamosCapitalDeInversionRoute,
  PrestamosConsolidacionDeDeudasRoute: PrestamosConsolidacionDeDeudasRoute,
  PrestamosPrestamoPersonalRoute: PrestamosPrestamoPersonalRoute,
  PrestamosRemodelacionDeInmuebleRoute: PrestamosRemodelacionDeInmuebleRoute,
}

const PrestamosRouteWithChildren = PrestamosRoute._addFileChildren(
  PrestamosRouteChildren,
)

interface PropiedadesRouteChildren {
  PropiedadesPropertyIdRoute: typeof PropiedadesPropertyIdRoute
  PropiedadesIndexRoute: typeof PropiedadesIndexRoute
}

const PropiedadesRouteChildren: PropiedadesRouteChildren = {
  PropiedadesPropertyIdRoute: PropiedadesPropertyIdRoute,
  PropiedadesIndexRoute: PropiedadesIndexRoute,
}

const PropiedadesRouteWithChildren = PropiedadesRoute._addFileChildren(
  PropiedadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalcularCreditoRoute: CalcularCreditoRoute,
  PrestamosRoute: PrestamosRouteWithChildren,
  PropiedadesRoute: PropiedadesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
